metrics:
    unit_of_work.compute_change_set:
        label: 'UnitOfWork ComputeChangeSet'
        description: 'Metric for amount of times UnitOfWork ComputeChangeSet is called'

        matching_calls:
            php:
                -
                    callee: "=Doctrine\\ORM\\UnitOfWork::computeChangeSet"

tests:
    "The homepage should be fast":
        path: "/"
        assertions:
            - "main.wall_time < 200ms"

    "The comments should not be loaded in separate queries":
        path: "/sighting/.*"
        assertions:
            - "metrics.sql.queries.count < 5"

    "UnitOfWork should not be overworked":
        path: ".*"
        command: ".*"
        assertions:
            - "metrics.unit_of_work.compute_change_set.count < 100000"
